/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EncounterIdRouteImport } from './routes/$encounterId'
import { Route as IndexRouteImport } from './routes/index'

const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EncounterIdRoute = EncounterIdRouteImport.update({
  id: '/$encounterId',
  path: '/$encounterId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$encounterId': typeof EncounterIdRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$encounterId': typeof EncounterIdRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$encounterId': typeof EncounterIdRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$encounterId' | '/login' | '/parties'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$encounterId' | '/login' | '/parties'
  id: '__root__' | '/' | '/$encounterId' | '/login' | '/parties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncounterIdRoute: typeof EncounterIdRoute
  LoginRoute: typeof LoginRoute
  PartiesRoute: typeof PartiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$encounterId': {
      id: '/$encounterId'
      path: '/$encounterId'
      fullPath: '/$encounterId'
      preLoaderRoute: typeof EncounterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncounterIdRoute: EncounterIdRoute,
  LoginRoute: LoginRoute,
  PartiesRoute: PartiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
